### PR TITLE
Added floating point multiply without accidentally overwriting Makefile

### PR DESCRIPTION
**Pull request by dillonhuff**
Should work this time

### CODE REVIEW

**Comment by jeffsetter** [comment]
Is there any progress related to the other desired instructions? This feature will help a lot to isolating problems using BFloat in the Halide compiler.
https://github.com/rdaly525/coreir/issues/727

**Comment by dillonhuff** [comment]
@jeffsetter I have not been working on it, but several operations (eq, neq, sgn, and abs) could also be implemented very quickly.

Transcendentals and rounding related ops will take longer. Which operations do you need?

**Comment by jeffsetter** [comment]
Eventually all of them will be needed, since these are the operations that we will have on our CGRA. The list of those operations are here: https://github.com/rdaly525/coreir/issues/727

Div and comparisons will be most helpful for the applications we have right now though.

**Comment by dillonhuff** [comment]
@rdaly525 I am trying to get this PR up to date but I am getting an error about unauthenticated packages on travis. Do you have any idea what is wrong?

**Comment by rdaly525** [comment]
Not quite sure... Could possibly be related to #736 as I just merged that. I am rebuilding to see if it is an intermittent travis error

**Comment by dillonhuff** [comment]
@rdaly525 it appears that it was a travis error. Can you merge this PR so @jeffsetter can have access to the new float ops?

**Pull request merged**
