### PR TITLE
Use RPATH ORIGIN

### PR DESCRIPTION
**Pull request by rsetaluri**

### CODE REVIEW

**Comment by hofstee** [comment]
Why did we even need to deal with RPATH in the first place? I know the modifications I made earlier were because if you did `make install` followed by `make clean` then things would break. But what about originally? Seems like it's causing a fair number of the headaches in the build script.

**Comment by rsetaluri** [comment]
at this point, I think things are just a patch work of getting things tot work in various cases. Not sure of the original reason for us, but generally it allows to set the search path at link time.

I'm using origin (search "ORIGIN" in http://man7.org/linux/man-pages/man8/ld.so.8.html) because the search path should be relative to the original build location.

**Comment by rdaly525** [comment]
@hofstee The reason for using rpath is so that coreir can do runtime loading of the coreir libraries like commonlib.

**Comment by rsetaluri** [comment]
Going to use a different approach to fix this...

**Pull request closed without merging**
