### PR TITLE
Fix Simulator Plugin in Interpreter for Running H2H Simulation

### PR DESCRIPTION
**Pull request by joyliu37**
I make a small changes in interpreter.cpp to make memory rewrite could be simulated.

### CODE REVIEW

**Comment by rsetaluri** [comment]
@joyliu37 can you clean this PR up and reduce it to just the things relevant to your change? It looks like a lot of extraneous things in here; including effects of a merge. you should rebase on master too.

**Comment by rdaly525** [comment]
@joyliu37, agreed with @rsetaluri, could you do the master rebase?

**Comment by joyliu37** [comment]
Should I do `git rebase master` instead of `git merge master`. Sorry about that, I have poor git knowledge.

**Comment by rdaly525** [comment]
rebase is preferable, but sometimes that is too ridiculous, so I often find myself doing the following:
```
>git checkout master
>get pull
>get checkout <my_branch>
>git merge master
>git reset master
>git add <your changes>
>git commit
>git push -f
```

Basically this gets your branch up to date with master and gives it a clean commit history. The local changes should still be there, but requires you to re add/commit.

**Comment by rsetaluri** [comment]
@joyliu37 see #875. please work off that if it is appropriate. In this case I think a rebase is best.

Also, your editor seems to be automatically cleaning up whitespace -- please do not commit the changes caused by that. Make sure whatever you add and commit is actually what is relevant for your change. I *recommend against* `git commit -a`.

**Comment by joyliu37** [comment]
I also found the whitespace substitute issue. I will check your commit.

**Comment by rsetaluri** [comment]
Closing in favor of #875

**Pull request closed without merging**
