### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by rdaly525**
This includes the cmake changes. Since the build process for CoreIR is now via cmake, this will likely break some repos (pycoreir, magma, Halide, etc...).

@leonardt, and @jeffsetter, could you investigate if and how this change will affect your repos?
@cdonovick, feel free to review my cmake changes if you would like.

### CODE REVIEW

**Comment by jeffsetter** [comment]
I'll take a look. It will likely mean just fixing the travis scripts for Halide-to-Hardware and CGRAFlow to use cmake to install coreir.

**Comment by leonardt** [comment]
pycoreir dev branch is passing on travis with the new cmake build commands (changes part of https://github.com/leonardt/pycoreir/pull/77)

**Comment by leonardt** [comment]
magma works as well (mantle uses the same script as magma) https://github.com/phanrahan/magma/pull/376

**Comment by rdaly525** [comment]
@jeffsetter, do you have a halide branch that works with this dev?

**Comment by rdaly525** [comment]
https://github.com/StanfordAHA/Halide-to-Hardware/pull/4 After this is merged, I will do coreir dev->master and do a release

**Pull request merged**
