### PR TITLE
added clang-format

### PR DESCRIPTION
**Pull request by rdaly525**
This is a start for the repo cleanup effort. Eventually I would like to force all C++ files to adhere to this.

### CODE REVIEW

**Comment by leonardt** [comment]
I'm not too picky on style specifics as long as it's consistent (and automated).  Perhaps we can just this PR to do a big run over the code base to clang-format everything in one go?

**Comment by rdaly525** [comment]
> I'm not too picky on style specifics as long as it's consistent (and automated). Perhaps we can just this PR to do a big run over the code base to clang-format everything in one go?

Totally agree. Just wanted to get both of you on board with the .clang-format file before doing it.

**Comment by rdaly525** [comment]
@rsetaluri I would need to test these out, but as long as at minimum it does what I have in my clang-format, I am amenable.

**Comment by rdaly525** [comment]
https://reviews.llvm.org/D33029 I would also love to add this feature but it is unfortunately not merged yet :(

**Comment by rsetaluri** [comment]
@rdaly525 compare to #869

**Comment by rsetaluri** [comment]
Solved by #879

**Pull request closed without merging**
