### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by rdaly525**
Major:
syntax checking
json changes
Added BitInOut type

### CODE REVIEW

**Comment by rdaly525** [comment]
https://travis-ci.org/StanfordAHA/CGRAFlow/jobs/343973964 
@leonardt, it looks like something is strange with COREWireableGetModuleDef. It might need to be updated in pycoreir. could you take a look?

**Comment by leonardt** [comment]
Pycoreir tracked at https://github.com/leonardt/pycoreir/pull/25

**Comment by leonardt** [comment]
Magma at https://github.com/phanrahan/magma/pull/138

**Comment by leonardt** [comment]
Mantle at https://github.com/phanrahan/mantle/pull/56

**Pull request merged**
