### PR TITLE
Require that generator params/args be a superset of typegen params

### PR DESCRIPTION
**Pull request by THofstee**
This is a fix for issue #27.

### CODE REVIEW

**Comment by THofstee** [comment]
Retargeted onto dev.

**Comment by THofstee** [comment]
I think `checkArgs` might be a better name than `checkParams`, but I'm not sure if that's the best name for this.

**Comment by THofstee** [comment]
Out of curiosity, what would be the reasoning for having another function test whether or not they are exactly equal?

**Comment by rdaly525** [comment]
I do the matching check on the Args being passed into the generator. Is there a good situation where you would want to pass in more args to a generator instance than the generator needed? Perhaps?
I do totally agree that the typegen should be a subset of the generator args.

**Comment by THofstee** [comment]
I'm not sure. Previously in the other branch I was working in I used it out of convenience because I didn't need a type to pass into runGenerator, but I would get a segfault if I passed in a nullptr so I just grabbed the TypeGen for the Generator and ran it with the arguments for the generator.

I think it's probably better to only have the equality check instead of subset when you provide arguments to the parameters. I can't think of any programming languages that allow you to pass in more arguments to a function than the function has parameters, and I can imagine a lot of nasty bugs that might result from this.

I'll need to double check to see if the nullptr passed to runGenerator still causes a segfault in the dev branch. I'll clean this up a bit tomorrow.

**Comment by rdaly525** [comment]
Just as a warning, I did clean up the infrastructure for running the typegen and generator functions a bit. I made them into an actual method of the class rather than a random function (although I did keep that ability to pass in a random function). If the API is not clear, definitely let me know and add it to Issue #33.  Also if you are getting segfaults, then definitely report an issue. Ideally you should not be able to segfault.

**Comment by rdaly525** [comment]
Thanks again for looking into this stuff! I know it is annoying that things keeps changing, but that is the definition of Agile!

**Comment by THofstee** [comment]
Seeing as how there is only one function now to check that args exactly match params, I've just left it renamed `checkArgs` similar to other compilers.

**Pull request merged**
