### PR TITLE
Interpreter cycle counter

### PR DESCRIPTION
**Pull request by dillonhuff**
At the request of @shacklettbp I have added a cycle counter. You can now read out total cycles executed by the clock. As part of this change the simulator now automatically detects the main clock and crashes with an error if the circuit has more than clock.

For example, if the circuit has one clock named "self.clk" you can get the number of cycles executed like so:

```cpp
ClockValue* clk = toClock(state.getValue("self.clk"));
int cycleCount = clk->getCycleCount();
```

### CODE REVIEW

**Comment by dillonhuff** [comment]
*more than one clock

**Comment by rdaly525** [comment]
Instead of checking for the name self.clk, can you check for a signal of type corer.clk ?

**Comment by dillonhuff** [comment]
A signal with type ```coreir.clk``` is what I check for in ```findMainClock()``` this is just an example where the name of the main clock happens to be ```self.clk```

**Comment by rdaly525** [comment]
@dillonhuff Can you resolve the conflicts?

**Pull request merged**
